blank_issues_enabled: false
contact_links:
  - name: Fragen & Hilfe
    url: https://github.com/Panicgrinder/Novapolis-RP/discussions
    about: FÃ¼r allgemeine Fragen oder ideen bitte die Discussions nutzen.